INTENT_OTP_POLICY = {
    "HIGH_BILL": True,
    "AVERAGE_BILL": False,
    "METER_RELATED_ISSUE": True,
    "CHANGE_OF_TARIFF": True,
    "NON_RECEIPT_OF_BILL": False,
    "REISSUE_REUSE_LESS_USE": False,
    "PAYMENT_RELATED": True,
    "SECURITY_DEPOSIT_REFUND": True,
    "VOLUNTARY_DISCONNECTION": True,
    "AMENDMENT_NAME_ADDRESS": True,
    "CHANGE_OF_NAME": True,
    "RECONNECTION": True,
    "CLARIFICATION": False
}